ALTER TABLE [Res_MainExamMarkSetup] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Res_MainExamMarkSetup] DISABLE TRIGGER ALL  
DELETE FROM [Res_MainExamMarkSetup]  

ALTER TABLE [Res_GrandExam] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Res_GrandExam] DISABLE TRIGGER ALL  
DELETE FROM [Res_GrandExam]  
ALTER TABLE [Res_GrandExam] CHECK CONSTRAINT ALL  
ALTER TABLE [Res_GrandExam] ENABLE TRIGGER ALL
IF NOT EXISTS (SELECT *
    FROM SYS.IDENTITY_COLUMNS
    JOIN SYS.TABLES ON SYS.IDENTITY_COLUMNS.Object_ID = SYS.TABLES.Object_ID
    WHERE SYS.TABLES.Object_ID = OBJECT_ID('[Res_GrandExam]') AND SYS.IDENTITY_COLUMNS.Last_Value IS NULL)
    AND OBJECTPROPERTY(OBJECT_ID('[Res_GrandExam]'), 'TableHasIdentity') = 1
    DBCC CHECKIDENT ('[Res_GrandExam]', RESEED, 0) WITH NO_INFOMSGS

TRUNCATE TABLE  Att_AbscondingDetails
TRUNCATE TABLE  Res_GrandMeritListConfig
TRUNCATE TABLE  Att_AcademicCalendar
TRUNCATE TABLE  Res_GrandSetup
TRUNCATE TABLE  Att_ExamAttendance
TRUNCATE TABLE  Res_GrandStudentAssessment
TRUNCATE TABLE  Att_LeaveTypes

ALTER TABLE [Res_GrandSubExam] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Res_GrandSubExam] DISABLE TRIGGER ALL  
DELETE FROM [Res_GrandSubExam]  
ALTER TABLE [Res_GrandSubExam] CHECK CONSTRAINT ALL  
ALTER TABLE [Res_GrandSubExam] ENABLE TRIGGER ALL
IF NOT EXISTS (SELECT *
    FROM SYS.IDENTITY_COLUMNS
    JOIN SYS.TABLES ON SYS.IDENTITY_COLUMNS.Object_ID = SYS.TABLES.Object_ID
    WHERE SYS.TABLES.Object_ID = OBJECT_ID('[Res_GrandSubExam]') AND SYS.IDENTITY_COLUMNS.Last_Value IS NULL)
    AND OBJECTPROPERTY(OBJECT_ID('[Res_GrandSubExam]'), 'TableHasIdentity') = 1
    DBCC CHECKIDENT ('[Res_GrandSubExam]', RESEED, 0) WITH NO_INFOMSGS

TRUNCATE TABLE  Att_StudentAttendance
TRUNCATE TABLE  Res_GrandVirtualExamSetup
TRUNCATE TABLE  Att_StudentLeave
TRUNCATE TABLE  Att_StudentLIEO
TRUNCATE TABLE  Res_MainExamLeaveStudent
TRUNCATE TABLE  Att_StudentPeriodAtten
TRUNCATE TABLE  Res_MainExamMarks
TRUNCATE TABLE  Att_StudentPeriodLeave
TRUNCATE TABLE  Res_MarksMigratedSetup
TRUNCATE TABLE  Res_MeritListConfig
TRUNCATE TABLE  Emp_BasicInfo
TRUNCATE TABLE  Res_ReportConfig
TRUNCATE TABLE  Emp_Category
TRUNCATE TABLE  Res_Reports
TRUNCATE TABLE  Emp_ClassTeacher
TRUNCATE TABLE  Res_StudentSubject
TRUNCATE TABLE  Emp_Department
TRUNCATE TABLE  Res_TabConfig

ALTER TABLE [Res_MainExam] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Res_MainExam] DISABLE TRIGGER ALL  
DELETE FROM [Res_MainExam]  
ALTER TABLE [Res_MainExam] CHECK CONSTRAINT ALL  
ALTER TABLE [Res_MainExam] ENABLE TRIGGER ALL
IF NOT EXISTS (SELECT *
    FROM SYS.IDENTITY_COLUMNS
    JOIN SYS.TABLES ON SYS.IDENTITY_COLUMNS.Object_ID = SYS.TABLES.Object_ID
    WHERE SYS.TABLES.Object_ID = OBJECT_ID('[Res_MainExam]') AND SYS.IDENTITY_COLUMNS.Last_Value IS NULL)
    AND OBJECTPROPERTY(OBJECT_ID('[Res_MainExam]'), 'TableHasIdentity') = 1
    DBCC CHECKIDENT ('[Res_MainExam]', RESEED, 0) WITH NO_INFOMSGS

TRUNCATE TABLE  Emp_Designation
TRUNCATE TABLE  Res_Tabulation
TRUNCATE TABLE  Emp_EducationalInfo
TRUNCATE TABLE  Emp_ExamBoard
TRUNCATE TABLE  Res_VirtualExamSetup
TRUNCATE TABLE  Emp_ExamGroup
TRUNCATE TABLE  Rtn_ClassPeriod
TRUNCATE TABLE  Emp_ExamName
TRUNCATE TABLE  Rtn_PeriodTeacher
TRUNCATE TABLE  Emp_Image
TRUNCATE TABLE  SchoolSetups
TRUNCATE TABLE  Res_MainExamAssessment
TRUNCATE TABLE  Emp_Section
TRUNCATE TABLE  SMS_ScheduleSMSConfig
TRUNCATE TABLE  Student_AcademicInfo
TRUNCATE TABLE  Emp_Shift
TRUNCATE TABLE  SMS_Settings
TRUNCATE TABLE  Res_TempResult
TRUNCATE TABLE  Student_ContactInfo
TRUNCATE TABLE  Emp_Status
TRUNCATE TABLE  SMS_SMSExtGroup
TRUNCATE TABLE  Student_GuardianInfo
TRUNCATE TABLE  Fees_Setting
TRUNCATE TABLE  Emp_Subject

TRUNCATE TABLE  SMS_SMSExtNumbers
TRUNCATE TABLE  Student_Image
TRUNCATE TABLE  Fees_FeesSessionYear
TRUNCATE TABLE  Fees_AutomatedFeesConfig
TRUNCATE TABLE  SMS_SMSSendHistroy
TRUNCATE TABLE  Student_OthersInfo
TRUNCATE TABLE  Fees_ScholarshipType
TRUNCATE TABLE  Fees_Category
TRUNCATE TABLE  SMS_SMSTemplate
TRUNCATE TABLE  Student_PormotionHistory
TRUNCATE TABLE  Fees_ScholarshipMaster
TRUNCATE TABLE  Fees_CollectionDetails
TRUNCATE TABLE  SMS_SMSTempTag
TRUNCATE TABLE  Student_SiblingInfo
TRUNCATE TABLE  Fees_ScholarshipDetails
TRUNCATE TABLE  Fees_CollectionMaster
TRUNCATE TABLE  Fees_ReceiptSetting
TRUNCATE TABLE  Fees_DisplayGroup
TRUNCATE TABLE  Res_GrandResultSubjectDetails
TRUNCATE TABLE  Fees_ReceiptSettingDetails
TRUNCATE TABLE  Fees_DisplayGroupDetails

ALTER TABLE [Res_SubjectSetup] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Res_SubjectSetup] DISABLE TRIGGER ALL  
DELETE FROM [Res_SubjectSetup]  
ALTER TABLE [Res_SubjectSetup] CHECK CONSTRAINT ALL  
ALTER TABLE [Res_SubjectSetup] ENABLE TRIGGER ALL
IF NOT EXISTS (SELECT *
    FROM SYS.IDENTITY_COLUMNS
    JOIN SYS.TABLES ON SYS.IDENTITY_COLUMNS.Object_ID = SYS.TABLES.Object_ID
    WHERE SYS.TABLES.Object_ID = OBJECT_ID('[Res_SubjectSetup]') AND SYS.IDENTITY_COLUMNS.Last_Value IS NULL)
    AND OBJECTPROPERTY(OBJECT_ID('[Res_SubjectSetup]'), 'TableHasIdentity') = 1
    DBCC CHECKIDENT ('[Res_SubjectSetup]', RESEED, 0) WITH NO_INFOMSGS

TRUNCATE TABLE  Fees_FeesBooth
TRUNCATE TABLE  Res_GrandResult
TRUNCATE TABLE  Res_HighestMarkConfig
TRUNCATE TABLE  Fees_FeesLatePaySlab
TRUNCATE TABLE  Res_GrandResultMarksDetails
TRUNCATE TABLE  Ins_Signature
TRUNCATE TABLE  Fees_FeesModifyLog
TRUNCATE TABLE  Arch_ResultArchive

ALTER TABLE [Fees_FeesMonth] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Fees_FeesMonth] DISABLE TRIGGER ALL  
DELETE FROM [Fees_FeesMonth]  
ALTER TABLE [Fees_FeesMonth] CHECK CONSTRAINT ALL  
ALTER TABLE [Fees_FeesMonth] ENABLE TRIGGER ALL
IF NOT EXISTS (SELECT *
    FROM SYS.IDENTITY_COLUMNS
    JOIN SYS.TABLES ON SYS.IDENTITY_COLUMNS.Object_ID = SYS.TABLES.Object_ID
    WHERE SYS.TABLES.Object_ID = OBJECT_ID('[Fees_FeesMonth]') AND SYS.IDENTITY_COLUMNS.Last_Value IS NULL)
    AND OBJECTPROPERTY(OBJECT_ID('[Fees_FeesMonth]'), 'TableHasIdentity') = 1
    DBCC CHECKIDENT ('[Fees_FeesMonth]', RESEED, 0) WITH NO_INFOMSGS

TRUNCATE TABLE  Res_GrandSubExamMarkSetup
TRUNCATE TABLE  Res_ClassSubjectConfig
TRUNCATE TABLE  Fees_Head
TRUNCATE TABLE  Res_GrandDividedExamMarkSetup
TRUNCATE TABLE  Res_TempGrandResult
TRUNCATE TABLE  Res_Config
TRUNCATE TABLE  Fees_HeadAmountConfig
TRUNCATE TABLE  Res_GrandExamMarkSetup
TRUNCATE TABLE  Fees_HeadDefault

ALTER TABLE [Res_MainExamMarkSetup] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Res_MainExamMarkSetup] DISABLE TRIGGER ALL  
DELETE FROM [Res_MainExamMarkSetup]  
ALTER TABLE [Res_MainExamMarkSetup] CHECK CONSTRAINT ALL  
ALTER TABLE [Res_MainExamMarkSetup] ENABLE TRIGGER ALL
IF NOT EXISTS (SELECT *
    FROM SYS.IDENTITY_COLUMNS
    JOIN SYS.TABLES ON SYS.IDENTITY_COLUMNS.Object_ID = SYS.TABLES.Object_ID
    WHERE SYS.TABLES.Object_ID = OBJECT_ID('[Res_MainExamMarkSetup]') AND SYS.IDENTITY_COLUMNS.Last_Value IS NULL)
    AND OBJECTPROPERTY(OBJECT_ID('[Res_MainExamMarkSetup]'), 'TableHasIdentity') = 1
    DBCC CHECKIDENT ('[Res_MainExamMarkSetup]', RESEED, 0) WITH NO_INFOMSGS

TRUNCATE TABLE  Fees_HeadPriority

ALTER TABLE [Res_SubExamMarkSetup] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Res_SubExamMarkSetup] DISABLE TRIGGER ALL  
DELETE FROM [Res_SubExamMarkSetup]  
ALTER TABLE [Res_SubExamMarkSetup] CHECK CONSTRAINT ALL  
ALTER TABLE [Res_SubExamMarkSetup] ENABLE TRIGGER ALL
IF NOT EXISTS (SELECT *
    FROM SYS.IDENTITY_COLUMNS
    JOIN SYS.TABLES ON SYS.IDENTITY_COLUMNS.Object_ID = SYS.TABLES.Object_ID
    WHERE SYS.TABLES.Object_ID = OBJECT_ID('[Res_SubExamMarkSetup]') AND SYS.IDENTITY_COLUMNS.Last_Value IS NULL)
    AND OBJECTPROPERTY(OBJECT_ID('[Res_SubExamMarkSetup]'), 'TableHasIdentity') = 1
    DBCC CHECKIDENT ('[Res_SubExamMarkSetup]', RESEED, 0) WITH NO_INFOMSGS

TRUNCATE TABLE  Fees_Process
TRUNCATE TABLE  Res_DividedExamMarkSetup
TRUNCATE TABLE  Fees_ProcessDetails
TRUNCATE TABLE  Res_MainExamResult
TRUNCATE TABLE  Fees_Student
TRUNCATE TABLE  Res_MainExamResultSubjectDetails
TRUNCATE TABLE  Fees_StudentArchive
TRUNCATE TABLE  Res_MEResultDetails
TRUNCATE TABLE  Fees_TempCollection
TRUNCATE TABLE  Ins_AcademicBatch


ALTER TABLE [Res_SubExam] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Res_SubExam] DISABLE TRIGGER ALL  
DELETE FROM [Res_SubExam]  
ALTER TABLE [Res_SubExam] CHECK CONSTRAINT ALL  
ALTER TABLE [Res_SubExam] ENABLE TRIGGER ALL
IF NOT EXISTS (SELECT *
    FROM SYS.IDENTITY_COLUMNS
    JOIN SYS.TABLES ON SYS.IDENTITY_COLUMNS.Object_ID = SYS.TABLES.Object_ID
    WHERE SYS.TABLES.Object_ID = OBJECT_ID('[Res_SubExam]') AND SYS.IDENTITY_COLUMNS.Last_Value IS NULL)
    AND OBJECTPROPERTY(OBJECT_ID('[Res_SubExam]'), 'TableHasIdentity') = 1
    DBCC CHECKIDENT ('[Res_SubExam]', RESEED, 0) WITH NO_INFOMSGS

ALTER TABLE [Ins_AcademicDepartment] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Ins_AcademicDepartment] DISABLE TRIGGER ALL  
DELETE FROM [Ins_AcademicDepartment]  
ALTER TABLE [Ins_AcademicDepartment] CHECK CONSTRAINT ALL  
ALTER TABLE [Ins_AcademicDepartment] ENABLE TRIGGER ALL
IF NOT EXISTS (SELECT *
    FROM SYS.IDENTITY_COLUMNS
    JOIN SYS.TABLES ON SYS.IDENTITY_COLUMNS.Object_ID = SYS.TABLES.Object_ID
    WHERE SYS.TABLES.Object_ID = OBJECT_ID('[Ins_AcademicDepartment]') AND SYS.IDENTITY_COLUMNS.Last_Value IS NULL)
    AND OBJECTPROPERTY(OBJECT_ID('[Ins_AcademicDepartment]'), 'TableHasIdentity') = 1
    DBCC CHECKIDENT ('[Ins_AcademicDepartment]', RESEED, 0) WITH NO_INFOMSGS


TRUNCATE TABLE  Res_DividedExam
TRUNCATE TABLE  Ins_AcademicProgram
TRUNCATE TABLE  Ins_AcademicSemester

ALTER TABLE [Ins_Branch] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Ins_Branch] DISABLE TRIGGER ALL  
DELETE FROM [Ins_Branch]  
ALTER TABLE [Ins_Branch] CHECK CONSTRAINT ALL  
ALTER TABLE [Ins_Branch] ENABLE TRIGGER ALL
IF NOT EXISTS (SELECT *
    FROM SYS.IDENTITY_COLUMNS
    JOIN SYS.TABLES ON SYS.IDENTITY_COLUMNS.Object_ID = SYS.TABLES.Object_ID
    WHERE SYS.TABLES.Object_ID = OBJECT_ID('[Ins_Branch]') AND SYS.IDENTITY_COLUMNS.Last_Value IS NULL)
    AND OBJECTPROPERTY(OBJECT_ID('[Ins_Branch]'), 'TableHasIdentity') = 1
    DBCC CHECKIDENT ('[Ins_Branch]', RESEED, 0) WITH NO_INFOMSGS

ALTER TABLE [Ins_AcaProCategory] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Ins_AcaProCategory] DISABLE TRIGGER ALL  
DELETE FROM [Ins_AcaProCategory]  
ALTER TABLE [Ins_AcaProCategory] CHECK CONSTRAINT ALL  
ALTER TABLE [Ins_AcaProCategory] ENABLE TRIGGER ALL
IF NOT EXISTS (SELECT *
    FROM SYS.IDENTITY_COLUMNS
    JOIN SYS.TABLES ON SYS.IDENTITY_COLUMNS.Object_ID = SYS.TABLES.Object_ID
    WHERE SYS.TABLES.Object_ID = OBJECT_ID('[Ins_AcaProCategory]') AND SYS.IDENTITY_COLUMNS.Last_Value IS NULL)
    AND OBJECTPROPERTY(OBJECT_ID('[Ins_AcaProCategory]'), 'TableHasIdentity') = 1
    DBCC CHECKIDENT ('[Ins_AcaProCategory]', RESEED, 0) WITH NO_INFOMSGS

ALTER TABLE [Ins_ClassInfo] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Ins_ClassInfo] DISABLE TRIGGER ALL  
DELETE FROM [Ins_ClassInfo]  
ALTER TABLE [Ins_ClassInfo] CHECK CONSTRAINT ALL  
ALTER TABLE [Ins_ClassInfo] ENABLE TRIGGER ALL
IF NOT EXISTS (SELECT *
    FROM SYS.IDENTITY_COLUMNS
    JOIN SYS.TABLES ON SYS.IDENTITY_COLUMNS.Object_ID = SYS.TABLES.Object_ID
    WHERE SYS.TABLES.Object_ID = OBJECT_ID('[Ins_ClassInfo]') AND SYS.IDENTITY_COLUMNS.Last_Value IS NULL)
    AND OBJECTPROPERTY(OBJECT_ID('[Ins_ClassInfo]'), 'TableHasIdentity') = 1
    DBCC CHECKIDENT ('[Ins_ClassInfo]', RESEED, 0) WITH NO_INFOMSGS

TRUNCATE TABLE  Ins_AdmitCardSetup

ALTER TABLE [Ins_Group] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Ins_Group] DISABLE TRIGGER ALL  
DELETE FROM [Ins_Group]  
ALTER TABLE [Ins_Group] CHECK CONSTRAINT ALL  
ALTER TABLE [Ins_Group] ENABLE TRIGGER ALL
IF NOT EXISTS (SELECT *
    FROM SYS.IDENTITY_COLUMNS
    JOIN SYS.TABLES ON SYS.IDENTITY_COLUMNS.Object_ID = SYS.TABLES.Object_ID
    WHERE SYS.TABLES.Object_ID = OBJECT_ID('[Ins_Group]') AND SYS.IDENTITY_COLUMNS.Last_Value IS NULL)
    AND OBJECTPROPERTY(OBJECT_ID('[Ins_Group]'), 'TableHasIdentity') = 1
    DBCC CHECKIDENT ('[Ins_Group]', RESEED, 0) WITH NO_INFOMSGS

TRUNCATE TABLE  Ins_House
TRUNCATE TABLE  Ins_Section
TRUNCATE TABLE  Ins_IDConfig

ALTER TABLE [Ins_Session] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Ins_Session] DISABLE TRIGGER ALL  
DELETE FROM [Ins_Session]
ALTER TABLE [Ins_Session] CHECK CONSTRAINT ALL  
ALTER TABLE [Ins_Session] ENABLE TRIGGER ALL
IF NOT EXISTS (SELECT *
    FROM SYS.IDENTITY_COLUMNS
    JOIN SYS.TABLES ON SYS.IDENTITY_COLUMNS.Object_ID = SYS.TABLES.Object_ID
    WHERE SYS.TABLES.Object_ID = OBJECT_ID('[Ins_Session]') AND SYS.IDENTITY_COLUMNS.Last_Value IS NULL)
    AND OBJECTPROPERTY(OBJECT_ID('[Ins_Session]'), 'TableHasIdentity') = 1
    DBCC CHECKIDENT ('[Ins_Session]', RESEED, 0) WITH NO_INFOMSGS


TRUNCATE TABLE  Ins_ReportHeader
TRUNCATE TABLE  Ins_Shift
TRUNCATE TABLE  Ins_Route
TRUNCATE TABLE  Ins_ScholarshipType
TRUNCATE TABLE  Ins_SeatCardSetup
TRUNCATE TABLE  Ins_StudentType

ALTER TABLE [Student_BasicInfo] NOCHECK CONSTRAINT ALL  
ALTER TABLE [Student_BasicInfo] DISABLE TRIGGER ALL  
DELETE FROM [Student_BasicInfo]
ALTER TABLE [Student_BasicInfo] CHECK CONSTRAINT ALL  
ALTER TABLE [Student_BasicInfo] ENABLE TRIGGER ALL
IF NOT EXISTS (SELECT *
    FROM SYS.IDENTITY_COLUMNS
    JOIN SYS.TABLES ON SYS.IDENTITY_COLUMNS.Object_ID = SYS.TABLES.Object_ID
    WHERE SYS.TABLES.Object_ID = OBJECT_ID('[Student_BasicInfo]') AND SYS.IDENTITY_COLUMNS.Last_Value IS NULL)
    AND OBJECTPROPERTY(OBJECT_ID('[Student_BasicInfo]'), 'TableHasIdentity') = 1
    DBCC CHECKIDENT ('[Student_BasicInfo]', RESEED, 0) WITH NO_INFOMSGS


TRUNCATE TABLE  Ins_TC_Template
TRUNCATE TABLE  Res_AssessmentSubject
TRUNCATE TABLE  Res_AssignSubjectsToTeacher
TRUNCATE TABLE  Res_ConvertedPositionSetup
TRUNCATE TABLE  Res_ExamProccessLog
TRUNCATE TABLE  Res_FouthSubjectRules
TRUNCATE TABLE  Res_GradingSystem
TRUNCATE TABLE  Res_GrandConfig
TRUNCATE TABLE  Res_GrandDividedExam