namespace OEMS.Models.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class changes : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Ins_ClassInfo", "VersionId", "dbo.Ins_Version");
            DropForeignKey("dbo.Res_MainExamMarkSetup", "GroupId", "dbo.Ins_Group");
            DropForeignKey("dbo.Res_MainExamMarkSetup", "VersionId", "dbo.Ins_Version");
            DropIndex("dbo.Ins_ClassInfo", new[] { "VersionId" });
            DropIndex("dbo.Res_MainExamMarkSetup", new[] { "VersionId" });
            DropIndex("dbo.Res_MainExamMarkSetup", new[] { "GroupId" });
            RenameColumn(table: "dbo.Ins_ClassInfo", name: "VersionId", newName: "Version_VersionId");
            RenameColumn(table: "dbo.Res_MainExamMarkSetup", name: "GroupId", newName: "GroupInfo_GroupId");
            RenameColumn(table: "dbo.Res_MainExamMarkSetup", name: "VersionId", newName: "VersionInfo_VersionId");
            AddColumn("dbo.Ins_ECAClubConfig", "IsRepeatYear", c => c.Boolean(nullable: false));
            AddColumn("dbo.Stu_Clubs", "CategoryName", c => c.String());
            AddColumn("dbo.Stu_Clubs", "DayId", c => c.Int(nullable: false));
            AlterColumn("dbo.Ins_ClassInfo", "Version_VersionId", c => c.Int());
            AlterColumn("dbo.Res_MainExamMarkSetup", "VersionInfo_VersionId", c => c.Int());
            AlterColumn("dbo.Res_MainExamMarkSetup", "GroupInfo_GroupId", c => c.Int());
            CreateIndex("dbo.Ins_ClassInfo", "Version_VersionId");
            CreateIndex("dbo.Res_MainExamMarkSetup", "GroupInfo_GroupId");
            CreateIndex("dbo.Res_MainExamMarkSetup", "VersionInfo_VersionId");
            AddForeignKey("dbo.Ins_ClassInfo", "Version_VersionId", "dbo.Ins_Version", "VersionId");
            AddForeignKey("dbo.Res_MainExamMarkSetup", "GroupInfo_GroupId", "dbo.Ins_Group", "GroupId");
            AddForeignKey("dbo.Res_MainExamMarkSetup", "VersionInfo_VersionId", "dbo.Ins_Version", "VersionId");
            DropColumn("dbo.Ins_AdmitCardSetup", "VersionID");
            DropColumn("dbo.Res_AssessmentSubject", "VersionId");
            DropColumn("dbo.Res_AssignSubjectsToTeacher", "VersionID");
            DropColumn("dbo.Ins_ClassInfo", "IsWholeSession");
            DropColumn("dbo.Ins_ClassInfo", "IsWholeTerm");
            DropColumn("dbo.Res_MainExam", "VersionId");
            DropColumn("dbo.Res_MainExam", "GroupId");
            DropColumn("dbo.Res_SubjectSetup", "VersionID");
            DropColumn("dbo.Res_SubjectSetup", "GroupId");
            DropColumn("dbo.Rtn_ClassPeriod", "VersionId");
            DropColumn("dbo.Res_ClassSubjectConfig", "VersionId");
            DropColumn("dbo.Res_ClassSubjectConfig", "GroupId");
            DropColumn("dbo.Emp_ClassTeacher", "VersionId");
            DropColumn("dbo.Emp_ClassTeacher", "GroupId");
            DropColumn("dbo.Ins_ECAClubConfig", "VersionId");
            DropColumn("dbo.Ins_ECAClubConfig", "CategoryName");
            DropColumn("dbo.Res_ConvertedPositionSetup", "VersionID");
            DropColumn("dbo.Emp_BasicInfo", "VersionID");
            DropColumn("dbo.Res_ExamProccessLog", "VersionID");
            DropColumn("dbo.Res_ExamProccessLog", "GroupId");
            DropColumn("dbo.Fees_AutomatedFeesConfig", "VersionId");
            DropColumn("dbo.Fees_AutomatedFeesConfig", "GroupId");
            DropColumn("dbo.Fees_HeadAmountConfig", "VersionId");
            DropColumn("dbo.Fees_HeadAmountConfig", "GroupId");
            DropColumn("dbo.Fees_ReceiptSetting", "VersionId");
            DropColumn("dbo.Fees_ReceiptSetting", "GroupId");
            DropColumn("dbo.Res_FouthSubjectRules", "VersionID");
            DropColumn("dbo.Res_FouthSubjectRules", "GroupID");
            DropColumn("dbo.Res_GradingSystem", "VersionID");
            DropColumn("dbo.Fees_HeadPriority", "VersionId");
            DropColumn("dbo.Res_HighestMarkConfig", "VersionId");
            DropColumn("dbo.Res_HighestMarkConfig", "GroupId");
            DropColumn("dbo.Res_MainExamAssessment", "VersionID");
            DropColumn("dbo.Res_MainExamAssessment", "GroupID");
            DropColumn("dbo.Res_MainExamLeaveStudent", "VersionId");
            DropColumn("dbo.Res_MainExamLeaveStudent", "GroupId");
            DropColumn("dbo.Res_MainExamMarks", "VersionId");
            DropColumn("dbo.Res_MainExamMarks", "GroupId");
            DropColumn("dbo.Res_MarksMigratedSetup", "VersionID");
            DropColumn("dbo.Res_MeritListConfig", "VersionId");
            DropColumn("dbo.Res_MeritListConfig", "GroupId");
            DropColumn("dbo.Student_BasicInfo", "VersionID");
            DropColumn("dbo.Student_BasicInfo", "GroupId");
            DropColumn("dbo.Rtn_PeriodTeacher", "VersionId");
            DropColumn("dbo.Rtn_PeriodTeacher", "GroupId");
            DropColumn("dbo.Portal_Document", "VersionId");
            DropColumn("dbo.Arch_ResultArchive", "VersionID");
            DropColumn("dbo.Arch_ResultArchive", "GroupId");
            DropColumn("dbo.Ins_SeatCardSetup", "VersionID");
            DropColumn("dbo.Ins_Signature", "VersionID");
            DropColumn("dbo.Att_StudentLIEO", "VersionId");
            DropColumn("dbo.Att_StudentLIEO", "GroupId");
            DropColumn("dbo.Student_PormotionHistory", "VersionID");
            DropColumn("dbo.Student_PormotionHistory", "GroupId");
            DropColumn("dbo.Student_PormotionHistory", "PromotedVersionID");
            DropColumn("dbo.Student_PormotionHistory", "PromotedGroupId");
            DropColumn("dbo.Res_StudentSubject", "VersionID");
            DropColumn("dbo.Res_StudentSubject", "GroupId");
            DropColumn("dbo.Res_Tabulation", "VersionID");
            DropColumn("dbo.Res_Tabulation", "GroupId");
            DropColumn("dbo.Res_VirtualExamSetup", "VersionId");
            DropColumn("dbo.Res_VirtualExamSetup", "GroupId");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Res_VirtualExamSetup", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_VirtualExamSetup", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_Tabulation", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_Tabulation", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Res_StudentSubject", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_StudentSubject", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Student_PormotionHistory", "PromotedGroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Student_PormotionHistory", "PromotedVersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Student_PormotionHistory", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Student_PormotionHistory", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Att_StudentLIEO", "GroupId", c => c.Int());
            AddColumn("dbo.Att_StudentLIEO", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Ins_Signature", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Ins_SeatCardSetup", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Arch_ResultArchive", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Arch_ResultArchive", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Portal_Document", "VersionId", c => c.Int());
            AddColumn("dbo.Rtn_PeriodTeacher", "GroupId", c => c.Int());
            AddColumn("dbo.Rtn_PeriodTeacher", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Student_BasicInfo", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Student_BasicInfo", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Res_MeritListConfig", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_MeritListConfig", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_MarksMigratedSetup", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Res_MainExamMarks", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_MainExamMarks", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_MainExamLeaveStudent", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_MainExamLeaveStudent", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_MainExamAssessment", "GroupID", c => c.Int(nullable: false));
            AddColumn("dbo.Res_MainExamAssessment", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Res_HighestMarkConfig", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_HighestMarkConfig", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Fees_HeadPriority", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_GradingSystem", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Res_FouthSubjectRules", "GroupID", c => c.Int(nullable: false));
            AddColumn("dbo.Res_FouthSubjectRules", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Fees_ReceiptSetting", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Fees_ReceiptSetting", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Fees_HeadAmountConfig", "GroupId", c => c.Int());
            AddColumn("dbo.Fees_HeadAmountConfig", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Fees_AutomatedFeesConfig", "GroupId", c => c.Int());
            AddColumn("dbo.Fees_AutomatedFeesConfig", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_ExamProccessLog", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_ExamProccessLog", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Emp_BasicInfo", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Res_ConvertedPositionSetup", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Ins_ECAClubConfig", "CategoryName", c => c.String());
            AddColumn("dbo.Ins_ECAClubConfig", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Emp_ClassTeacher", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Emp_ClassTeacher", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_ClassSubjectConfig", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_ClassSubjectConfig", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Rtn_ClassPeriod", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_SubjectSetup", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_SubjectSetup", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Res_MainExam", "GroupId", c => c.Int(nullable: false));
            AddColumn("dbo.Res_MainExam", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Ins_ClassInfo", "IsWholeTerm", c => c.Boolean(nullable: false));
            AddColumn("dbo.Ins_ClassInfo", "IsWholeSession", c => c.Boolean(nullable: false));
            AddColumn("dbo.Res_AssignSubjectsToTeacher", "VersionID", c => c.Int(nullable: false));
            AddColumn("dbo.Res_AssessmentSubject", "VersionId", c => c.Int(nullable: false));
            AddColumn("dbo.Ins_AdmitCardSetup", "VersionID", c => c.Int(nullable: false));
            DropForeignKey("dbo.Res_MainExamMarkSetup", "VersionInfo_VersionId", "dbo.Ins_Version");
            DropForeignKey("dbo.Res_MainExamMarkSetup", "GroupInfo_GroupId", "dbo.Ins_Group");
            DropForeignKey("dbo.Ins_ClassInfo", "Version_VersionId", "dbo.Ins_Version");
            DropIndex("dbo.Res_MainExamMarkSetup", new[] { "VersionInfo_VersionId" });
            DropIndex("dbo.Res_MainExamMarkSetup", new[] { "GroupInfo_GroupId" });
            DropIndex("dbo.Ins_ClassInfo", new[] { "Version_VersionId" });
            AlterColumn("dbo.Res_MainExamMarkSetup", "GroupInfo_GroupId", c => c.Int(nullable: false));
            AlterColumn("dbo.Res_MainExamMarkSetup", "VersionInfo_VersionId", c => c.Int(nullable: false));
            AlterColumn("dbo.Ins_ClassInfo", "Version_VersionId", c => c.Int(nullable: false));
            DropColumn("dbo.Stu_Clubs", "DayId");
            DropColumn("dbo.Stu_Clubs", "CategoryName");
            DropColumn("dbo.Ins_ECAClubConfig", "IsRepeatYear");
            RenameColumn(table: "dbo.Res_MainExamMarkSetup", name: "VersionInfo_VersionId", newName: "VersionId");
            RenameColumn(table: "dbo.Res_MainExamMarkSetup", name: "GroupInfo_GroupId", newName: "GroupId");
            RenameColumn(table: "dbo.Ins_ClassInfo", name: "Version_VersionId", newName: "VersionId");
            CreateIndex("dbo.Res_MainExamMarkSetup", "GroupId");
            CreateIndex("dbo.Res_MainExamMarkSetup", "VersionId");
            CreateIndex("dbo.Ins_ClassInfo", "VersionId");
            AddForeignKey("dbo.Res_MainExamMarkSetup", "VersionId", "dbo.Ins_Version", "VersionId", cascadeDelete: true);
            AddForeignKey("dbo.Res_MainExamMarkSetup", "GroupId", "dbo.Ins_Group", "GroupId", cascadeDelete: true);
            AddForeignKey("dbo.Ins_ClassInfo", "VersionId", "dbo.Ins_Version", "VersionId", cascadeDelete: true);
        }
    }
}
