// <auto-generated />
namespace OEMS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TemporaryFieldAddEmpRoster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TemporaryFieldAddEmpRoster));
        
        string IMigrationMetadata.Id
        {
            get { return "201910221051365_TemporaryFieldAddEmpRoster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
