// <auto-generated />
namespace OEMS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addinvoicebillGeneretae151120202222 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addinvoicebillGeneretae151120202222));
        
        string IMigrationMetadata.Id
        {
            get { return "202011150706341_addinvoicebillGeneretae151120202222"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
