// <auto-generated />
namespace OEMS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcolDayAndDayTypeOnEmpRoster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcolDayAndDayTypeOnEmpRoster));
        
        string IMigrationMetadata.Id
        {
            get { return "202002101139173_addcolDayAndDayTypeOnEmpRoster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
