// <auto-generated />
namespace OEMS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AttendanceLog1502202111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AttendanceLog1502202111));
        
        string IMigrationMetadata.Id
        {
            get { return "202102151112526_AttendanceLog1502202111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
