// <auto-generated />
namespace OEMS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddcolumnDiscountLinkhead0202202101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddcolumnDiscountLinkhead0202202101));
        
        string IMigrationMetadata.Id
        {
            get { return "202102020612536_AddcolumnDiscountLinkhead0202202101"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
