//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [ClassName("AspNet Page")]
    public partial class AspNetPage
    {
        
        public AspNetPage()
        {
            this.AspNetPagesRoles = new HashSet<AspNetPagesRole>();
        }
        [Key]
        public int PageID { get; set; }
        public int ParentID { get; set; }
        public string NameOption_En { get; set; }
        public string NameOption_Bn { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Area { get; set; }
        public string IconClass { get; set; }
        public string ActiveLi { get; set; }
        public string Status { get; set; }
        public int Displayorder { get; set; }
        public Nullable<bool> IsParent { get; set; }

        public bool IsModule { get; set; }
        public int ModuleId { get; set; }


        public  ICollection<AspNetPagesRole> AspNetPagesRoles { get; set; }
    }
}
